Appropriate handling of arguments

diff --git a/bing/bing-wallpaper-dl_peapix b/bing/bing-wallpaper-dl_peapix
--- a/bing/bing-wallpaper-dl_peapix
+++ b/bing/bing-wallpaper-dl_peapix
@@ -162,7 +162,11 @@ function create_table() {
 #	0: OK(exist)
 #	1: NG(not exist)
 function check_table_existence() {
-    local table_name="$1"
+	if [[ ${#} -lt 1 ]]; then
+		echo "ERROR: Not enough args @ ${FUNCNAME[0]}()"
+		exit 1
+	fi
+    local table_name="${1}"
 
     local query="SELECT name FROM sqlite_master WHERE type='table' AND name='$table_name';"
     local result=$(sqlite3 "${DB_FILE}" "$query")
